Updated formula to 2.1 and added settings
Synthesis-Collective/EnemyReleveler pull request #7
Opened 2024-03-11 13:08 UTC by yan-bibiyan

This PR brings the changes from the 2.1 version of the zEdit patcher to the synthesis counterpart (2.1 reverts a change from 2.0, it removes the Math.Pow from the calculation, which was introduced in the synthesis version in the previous merge). This yielded a NaN in specific scenarios on my end, and apparently caused issues for users of the zEdit patcher as well - the main motivation for them to roll back the change. I've also fixed a potential division by zero issue introduced in the patcher with the extended enemy rules from the previous merge. Finally, I added some settings that make it possible to optionally add a global offset (like in the zEdit patcher), print debug output, or use a local file with your own custom enemy rules.

2024-03-13 19:26 UTC, Noggog requested changes

2024-03-13 19:26 UTC, Noggog commented on EnemyReleveler/Settings.cs
> +        public string FilePath { get; set; } = "C:\\enemy_rules.json";
Absolute path seems undesirable here.  Maybe we rename to `RelativeFilePath` and then just put `enemy_rules.json`.  The logic would then use this in combination with `state.ExtraSettingsDataPath` like it did before:
`var creatureRulesPath = Path.Combine(state.ExtraSettingsDataPath, "enemy_rules.json");`
except now it would look to the settings for the filename

2024-03-13 19:26 UTC, Noggog commented on EnemyReleveler/Settings.cs
> +        public bool UseLocalFile { get; set; } = false;
Maybe default this to `true`, so that the default behavior is as it was before -> looking to the file.
Could be convinced otherwise, tho

2024-03-13 19:27 UTC, Noggog commented
Thanks for the PR!  Looking solid overall, just some minor thoughts before we merge it in

2024-03-14 10:55 UTC, yan-bibiyan commented
> Thanks for the PR! Looking solid overall, just some minor thoughts before we merge it in

Thank you for taking the time to review the PR, and for your feedback! The more I think about that optional file configuration, the more I think it's redundant, regardless of whether I implement changes to it. I see little value, but interface pollution and potential to confuse the user in it now honestly, and I think it'll be best if I remove it from the settings altogether. In hindsight I feel it was an ill-informed decision and hastily done. Let me know if you think otherwise and you see value in keeping it around, and I'll be happy to implement the required changes!

2024-03-14 16:42 UTC, Noggog commented
I'm not too involved in it, so you'd know better than I if all the settings you can do in the file are expressed in the new settings, or if there's things you can only do in the file.

The other reason you might keep the file is if the settings involved are super long, and it would be tedious for a newcomer to re-type it all into the new system.  The file route would allow them to avoid the headache.

Those are my only thoughts, but I think you'd know best the route to take!

2024-03-14 16:42 UTC, Noggog approved these changes

2024-03-14 16:43 UTC, Noggog commented
I approved it.  Hopefully once you make any last changes you want to make you're able to hit the big merge button yourself now?   Let me know if you're not able to do that on your side.  Cheers!

2024-03-15 09:54 UTC, yan-bibiyan commented
> I approved it. Hopefully once you make any last changes you want to make you're able to hit the big merge button yourself now? Let me know if you're not able to do that on your side. Cheers!

Thank you again for your advice, it is appreciated regardless of your degree of involvement with this particular patcher. I went ahead and reverted my changes with regards to optional file configuration, this made the most sense. I don't have write access to the repo in order to merge the PR however, so if you can do that on my behalf it'd be greatly appreciated. Thanks again!

2024-03-15 20:24 UTC, merged